[rocks]

[plugins]
"rocks-config.nvim" = "3.1.0"
"rocks.nvim" = "2.44.0"
neorg = "9.3.0"
"rocks-git.nvim" = "2.5.3"
"plenary.nvim" = "0.1.4"
"nvim-lspconfig" = {git="neovim/nvim-lspconfig", rev="v1.8.0"}
"nvim-web-devicons" = "0.100"
"lualine.nvim" = "scm"
"alpha-nvim" = "scm"
"which-key.nvim" = "3.17.0"
"oil.nvim" = "2.15.0"
"mkdnflow.nvim" = {git = "jakewvincent/mkdnflow.nvim"}
"render-markdown.nvim" = {git = "MeanderingProgrammer/render-markdown.nvim"}
"image.nvim" = {git = "3rd/image.nvim"}
"diagram.nvim" = {git = "3rd/diagram.nvim"}
"gitsigns.nvim" = {git = "lewis6991/gitsigns.nvim", rev = "v1.0.2"}
"diffview.nvim" = {git = "sindrets/diffview.nvim"}

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.3"

[plugins.doom-one-nvim]
git = "NTBBloodbath/doom-one.nvim"

[plugins.telescope-nvim]
git = "nvim-telescope/telescope.nvim"
rev = "0.1.8"

[config]
plugins_dir = "plugins/"
auto_setup = false
